#!/usr/bin/env node
/**
 * Builds src/styles/tokens.css from docs/design/tokens/*.json (the source of truth).
 *
 * Naming:
 *   color.json primitive.*        -> --p-<path>
 *   color.json semantic.light.*   -> --color-<path>   (on :root)
 *   color.json semantic.dark.*    -> --color-<path>   (on :root.dark)
 *   color.json runtime.*          -> --<path>
 *   typography.json <group>.*     -> --<group>-<path> (e.g. --font-size-xs)
 *   space/size/radius/shadow      -> --space-*, --size-*, --radius-*, --shadow-*
 *
 * A leaf is any object with a "value" key. Keys starting with "$" are metadata.
 * References look like "{primitive.neutral.900}". An unresolved reference fails the build.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensDir = join(root, 'docs/design/tokens');
const outFile = join(root, 'src/styles/tokens.css');

const read = (name) => JSON.parse(readFileSync(join(tokensDir, name), 'utf8'));

/** Flattens a token tree into [[pathSegments, value], ...]. */
function flatten(node, path = []) {
  if (node && typeof node === 'object' && 'value' in node) return [[path, node.value]];
  return Object.entries(node ?? {})
    .filter(([key]) => !key.startsWith('$'))
    .flatMap(([key, child]) => flatten(child, [...path, key]));
}

const cssName = (prefix, path) => `--${[prefix, ...path].filter(Boolean).join('-')}`;

const color = read('color.json');
const primitivePaths = new Set(flatten(color.primitive).map(([path]) => ['primitive', ...path].join('.')));

function resolve(value, where) {
  if (typeof value !== 'string') return String(value);
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    if (!primitivePaths.has(ref)) {
      throw new Error(`Unresolved token reference {${ref}} in ${where}`);
    }
    return `var(${cssName('p', ref.split('.').slice(1))})`;
  });
}

const decl = (name, value) => `  ${name}: ${value};`;
const rootLines = [];
const darkLines = [];

for (const [path, value] of flatten(color.primitive)) rootLines.push(decl(cssName('p', path), value));
for (const [path, value] of flatten(color.semantic.light)) {
  rootLines.push(decl(cssName('color', path), resolve(value, `semantic.light.${path.join('.')}`)));
}
for (const [path, value] of flatten(color.semantic.dark)) {
  darkLines.push(decl(cssName('color', path), resolve(value, `semantic.dark.${path.join('.')}`)));
}
for (const [path, value] of flatten(color.runtime)) rootLines.push(decl(cssName('', path), value));

const typography = read('typography.json');
for (const [group, tree] of Object.entries(typography)) {
  if (group.startsWith('$')) continue;
  for (const [path, value] of flatten(tree)) rootLines.push(decl(cssName(group, path), value));
}

for (const [file, prefix] of [['space.json', 'space'], ['size.json', 'size']]) {
  for (const [path, value] of flatten(read(file)[prefix])) rootLines.push(decl(cssName(prefix, path), value));
}

const radiusShadow = read('radius-shadow.json');
for (const prefix of ['radius', 'shadow']) {
  for (const [path, value] of flatten(radiusShadow[prefix])) rootLines.push(decl(cssName(prefix, path), value));
}

const css = [
  '/* GENERATED by scripts/build-tokens.js from docs/design/tokens — do not edit. */',
  ':root {',
  ...rootLines,
  '}',
  '',
  ':root.dark {',
  ...(darkLines.length ? darkLines : ['  /* Dark theme deferred (gap T1): no reference yet. */']),
  '}',
  '',
].join('\n');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
console.log(`tokens: wrote ${rootLines.length + darkLines.length} custom properties to src/styles/tokens.css`);
